name: Payrocket Pull Request Build
on: pull_request
jobs:
  build:
    name: Assemble
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path:
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Assemble Debug
        run: ./gradlew assembleDebug
      - name: Lint Test
        run: ./gradlew lint
      - name: Build Project
        run: ./gradlew assemble

